### ISSUE TITLE
Cannot enumerate devices, method not supported

### ISSUE THREAD

**Issue by ricardoreveles3** [densen2014/ZXingBlazor#12]
<img width="679" alt="Captura de Pantalla 2022-03-28 a la(s) 17 04 35" src="https://user-images.githubusercontent.com/33937928/160502851-cfdcadd1-7d16-4036-8112-d78ef09133ed.png">

Im having a problem to scann codes as the library trows an error.

**Comment by densen2014** [comment]
The new version use [JavaScript isolation in JavaScript modules](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#javascript-isolation-in-javascript-modules)

Blazor enables JavaScript (JS) isolation in standard [JavaScript modules](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Modules) ([ECMAScript specification](https://tc39.es/ecma262/#sec-modules)).

JS isolation provides the following benefits:

- Imported JS no longer pollutes the global namespace.
- Consumers of a library and components aren't required to import the related JS.

----

[Destructive upgrade] The file Pages/_Host.cshtml or wasm project is wwwroot/index.html, no need to add references!!!!

If it is an upgrade from an older version, please remove the reference of zxing.js

!!REMOVE!! <script src="_content/ZXingBlazor/lib/barcodereader/zxing.js"></script>

!!REMOVE!! <script src="_content/ZXingBlazor/lib/barcodereader/barcode.js"></script>

.  enjoy !

**Comment by ricardoreveles3** [comment]
Thank you very much, I removed the scripts and no longer the error on load the JS is appear.
But the error "Cant enumerate the devices, method not supported" remains
<img width="675" alt="Captura de Pantalla 2022-03-29 a la(s) 8 52 04" src="https://user-images.githubusercontent.com/33937928/160640334-fe0a23f7-4f41-4e49-8e96-5071a45e0486.png">

**Comment by parente89** [comment]
I also encountered the same problem. The solution is to set the project in https otherwise device enumeration will not be possible.

**Currently, however, with the latest 0.21 update, if there are multiple acquisition devices connected, the plugin does not work. If there is only one device, it will boot quietly.**

**Comment by densen2014** [comment]
sent me a demo.zip

**Comment by densen2014** [comment]
run in a phone？

**Comment by ricardoreveles3** [comment]
On Mac (Latest update) and Google Chrome Versión 99.0.4844.84 (Build oficial) (x86_64)

**Comment by densen2014** [comment]
> Thank you very much, I removed the scripts and no longer the error on load the JS is appear. But the error "Cant enumerate the devices, method not supported" remains <img alt="Captura de Pantalla 2022-03-29 a la(s) 8 52 04" width="675" src="https://user-images.githubusercontent.com/33937928/160640334-fe0a23f7-4f41-4e49-8e96-5071a45e0486.png">

try using https

**Comment by densen2014** [comment]
> On Mac (Latest update) and Google Chrome Versión 99.0.4844.84 (Build oficial) (x86_64)

may MacPro with only buildin camara no ploblem. but ver 0.2.1 yes has a bug, i was fixed and publish a new 0.2.2

**Comment by densen2014** [comment]
1. Create a new projet
```
dotnet new blazorserver -o demo1
dotnet sln add demo1/demo1.csproj
dotnet add demo1 package ZXingBlazor
```

2. In Pages/Index.razor
```
@using ZXingBlazor.Components
<button class="btn btn-primary"
        type="button"
        @onclick="(() => ShowScanBarcode = !ShowScanBarcode)">
    [Sacn]
</button>
<input type="text" class="form-control" style="min-width: 100px;"
       @bind-value="BarCode"
       placeholder="BarCode" />
@if (ShowScanBarcode)
{

    <BarcodeReader ScanResult="((e) => { BarCode=e; ShowScanBarcode = !ShowScanBarcode; })"
                   ShowScanBarcode="ShowScanBarcode"
                   Close="(()=>ShowScanBarcode=!ShowScanBarcode)"
                   ScanBtnTitle="Scan"
                   ResetBtnTitle="Reset"
                   CloseBtnTitle="Close"
                   SelectDeviceBtnTitle="Select Device" />

}

@code{
    /// <summary>
    /// Display the scan code interface
    /// </summary>
    bool ShowScanBarcode { get; set; } = false;

    /// <summary>
    /// BarCode
    /// </summary>
    public string? BarCode { get; set; }

    private string message;

    private Task OnError(string message)
    {
        this.message = message;
        StateHasChanged();
        return Task.CompletedTask;
    }
}
```

3. Run
```
cd demo1
dotnet run
```

**Comment by ricardoreveles3** [comment]
<img width="1439" alt="Captura de Pantalla 2022-03-30 a la(s) 9 41 26" src="https://user-images.githubusercontent.com/33937928/160875842-851be229-23cf-4a96-9678-fcc73192eff1.png">

It has the same result

**Comment by densen2014** [comment]
try https://zxingblazor.app1.es/

**Comment by ricardoreveles3** [comment]
<img width="1435" alt="Captura de Pantalla 2022-03-30 a la(s) 11 05 13" src="https://user-images.githubusercontent.com/33937928/160891775-cfd4d818-37a6-46e6-9699-994ed50aa0d3.png">

The demo works fine

**Comment by densen2014** [comment]
> <img alt="Captura de Pantalla 2022-03-30 a la(s) 11 05 13" width="1435" src="https://user-images.githubusercontent.com/33937928/160891775-cfd4d818-37a6-46e6-9699-994ed50aa0d3.png">
> 
> The demo works fine

try run the source code =>[Demo.Server](https://github.com/densen2014/ZXingBlazor/tree/master/Demo.Server)

**Comment by ricardoreveles3** [comment]
When I run the demo locally works, but when I deployed to internet does not work

<img width="1432" alt="Captura de Pantalla 2022-03-30 a la(s) 11 58 30" src="https://user-images.githubusercontent.com/33937928/160900795-8e21bd1e-f276-49e3-9d9d-ad6fcc467f2a.png">

**Comment by ricardoreveles3** [comment]
Im using docker to deployed to internet

**Comment by densen2014** [comment]
> Im using docker to deployed to internet

try https 

**Security**
getUserMedia() can only be called from an HTTPS URL or localhost. Otherwise, the promise from the call is rejected. getUserMedia() also doesn't work for cross-origin calls from iframes. For more information, see [Deprecating Permissions in Cross-Origin Iframes](https://goo.gl/EuHzyv).

All browsers generate an infobar upon the call to getUserMedia(), which gives users the option to grant or deny access to their cameras or microphones. Here's the permission dialog from Chrome:

**Comment by densen2014** [comment]
> Im using docker to deployed to internet

i try link your ip to my https://blazor.app1.es/ it works fine!

**Comment by parente89** [comment]
Not work with more camera, for example in tablet

**Comment by densen2014** [comment]
it using https or not?

**Comment by parente89** [comment]
Https, but not even with the one published by you on github it works

**Comment by densen2014** [comment]
> Https, but not even with the one published by you on github it works

neither https://zxingblazor.app1.es/ ?

**Comment by parente89** [comment]
> Https, but not even with the one published by you on github it works

![Screenshot_2022-03-30-20-58-28-759_com android chrome](https://user-images.githubusercontent.com/73031092/160910388-6c84cef2-69fc-435d-9454-a335f19c08d5.jpg)


Yes

**Comment by densen2014** [comment]
try zxing officials demo

https://zxing-js.github.io/library/examples/barcode-camera/

**Comment by parente89** [comment]
> try zxing officials demo
> 
> https://zxing-js.github.io/library/examples/barcode-camera/

Yes it works

**Comment by densen2014** [comment]
interesting , what brand and model is the tablet?

**Comment by parente89** [comment]
> interesting , what brand and model is the tablet?

i tried with notebook with windows 10 and it doesn't work.  Lenovo tab m10 and not working.  Xiaomi mi notes 10 and it doesn't work

**Comment by parente89** [comment]
> interesting , what brand and model is the tablet?

however I want to clarify that up to 0.20 it worked normally, but it was not customizable
