### ISSUE TITLE
Pre-selection CameraDevice

### ISSUE THREAD

**Issue by FrankMuessner** [densen2014/ZXingBlazor#13]
Hello,
I have a question whether it is possible to automatically preselect the last selected camera device for the next scan?
My Samsung Flip-3 have 4 Cam´s, and only the 3. Cam scan Barcode. 
Is there a chance?
Regards, Frank

**Comment by densen2014** [comment]
try this https://www.blazor.zone/barcodereaders

I have merged this library into this project, see if I can help you


![image](https://user-images.githubusercontent.com/8428709/162021677-0ae6a098-d4e6-435e-8f95-5ee4eec0c6d5.png)

**Comment by FrankMuessner** [comment]
Thanks for the Link. Never see this Page :-)
