### ISSUE TITLE
Broken on sites that use a sub-url

### ISSUE THREAD

**Issue by gaelj** [densen2014/ZXingBlazor#16]
All my sites are hosted on the same server, each having its own sub-url.

Example:

- server.com/site1
- server.com/site2

Due to this I get 404s in production, because it's looking for resources at the root of the server. I guess all js lines similar to `import '/_content/ZXingBlazor/lib/zxing/zxing.min.js';` should have the first `/` removed.

**Comment by densen2014** [comment]
maybe change to import './_content/ZXingBlazor/lib/zxing/' will works for you?

if you can,run with source code and debug it. and PR it : )

**Comment by yablos** [comment]
This one worked for me on blazor server  project - .net60:
zxing.js
//import './_content/ZXingBlazor/lib/zxing/zxing.min.js';
change to:
import './zxing.min.js';

startup.cs:
app.UseHttpsRedirection();
app.UseStaticFiles() <-- important one

**Comment by densen2014** [comment]
> This one worked for me on blazor server project - .net60: zxing.js //import './_content/ZXingBlazor/lib/zxing/zxing.min.js'; change to: import './zxing.min.js';
> 
> startup.cs: app.UseHttpsRedirection(); app.UseStaticFiles() <-- important one

Thanks for shared!
