### ISSUE TITLE
Feature Request: Don't stop scanning after reading a QR code

### ISSUE THREAD

**Issue by jamieyello** [densen2014/ZXingBlazor#17]
In my application I need to scan multiple QR codes, so it would be good to have it just scan continuously and trigger the EventCallback many times if needed.

I have found a workaround, which is to immediately reset the form on reading a QR code, it does "work", but it's not really usable since it flickers.
![htttrhytrhtrjjj](https://user-images.githubusercontent.com/10054829/176787663-d36d9637-56cc-4706-8bea-b02736de6605.gif)

I have taken a look at the source code and unfortunately do not know enough about zxing to fork it and implement it myself, though if someone pointed me in the right direction I might be able to.

**Comment by densen2014** [comment]
try

    <BarcodeReader ScanResult='((e) => { BarCode=BarCode + "," + e; })'
                   ShowScanBarcode="ShowScanBarcode"
                   Close="(()=>ShowScanBarcode=!ShowScanBarcode)"
                   ScanBtnTitle="Scan"
                   ResetBtnTitle="Reset"
                   CloseBtnTitle="Close"
                   AutoStop="false"
                   SelectDeviceBtnTitle="Select Device" />

ShowScanBarcode is a switch for show UI

ScanResult='((e) => { BarCode=BarCode + "," + e; ShowScanBarcode = !ShowScanBarcode; })'

**Comment by densen2014** [comment]
v0.2.5

 Decodeonce="false"

```
    <BarcodeReader ScanResult="ScanResult"
                   ShowScanBarcode="ShowScanBarcode"
                   Close="(()=>ShowScanBarcode=!ShowScanBarcode)"
                   ScanBtnTitle="Scan"
                   ResetBtnTitle="Reset"
                   CloseBtnTitle="Close"
                   Decodeonce="false"
                   SelectDeviceBtnTitle="Select Device" />
```

![image](https://user-images.githubusercontent.com/8428709/203343701-db08d428-4018-413a-86c3-eb989bc0b9c8.png)

**Comment by jamieyello** [comment]
Cool 😎
