### ISSUE TITLE
Can you Scan 1D Barcodes

### ISSUE THREAD

**Issue by noumanqaiser** [densen2014/ZXingBlazor#18]
Hi, Thanks for such a useful barcode scanning utility for Blazor.

I dont seem to be able to scan 1D barcodes using the tool, is that something possible as a lot of applications still depend on 1D symbology barcodes.

if yes, can you guide how?

**Comment by densen2014** [comment]
In Readme.md has a gif

![image](https://user-images.githubusercontent.com/8428709/187805071-897f1cb9-f143-4ee4-85b5-06f1012f6cdf.png)
![image](https://user-images.githubusercontent.com/8428709/187805073-77a07da1-53d3-4ac6-8034-7b32dd4f65fd.png)

**Comment by dajma00** [comment]
Same issue. QR Code works fine, but cannot scan barcode (1D).

**Comment by densen2014** [comment]
sure it can be

**Comment by dajma00** [comment]
Ok, yes it scans. I think my barcode was bad or something. I tried some others from the web and it worked.
