### ISSUE TITLE
Mobile Blazor Binding

### ISSUE THREAD

**Issue by rajeshsws** [densen2014/ZXingBlazor#2]
Hi
Can we use this lib, for mobile blazor binding for android pro
I am getting a below error on lenovo tablet 
![20201216_210455](https://user-images.githubusercontent.com/48245007/102370070-a8acfc80-3fe2-11eb-951f-10e97bdb2810.jpg)

Camera is not coming

**Comment by densen2014** [comment]
Because Android or iOS can only use the native browser to have the permission to use the camera to obtain the stream scan barcode,it using h5 < video > label. And deployment to the Internet requires https. 

your mobile blazor binding is deployment in local network or Internet ? or xamarin?

**Comment by rajeshsws** [comment]
Hi Densen
Thnak you for quick response. Camera permission is already given , there is no permission issue.
 var status = await Permissions.CheckStatusAsync<Permissions.Camera>();


                    if (status != PermissionStatus.Granted)
                    {
                        status = await Permissions.RequestAsync<Permissions.Camera>();
                    }
                    if (status != PermissionStatus.Granted)
                    {
                        return;
                    }
also in Manifest.xml its given
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
	<uses-permission android:name="android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" />
I have tried on local same error is coming on ineternet is also coming same error.
Do you have nay future plan for mobile blazor binding project to make it happen.
There are lot of solution availabe but all thsoe are working for browser .
Thank you

**Comment by densen2014** [comment]
hi
your blazor binding is run on android localhost or in a https website?

**Comment by densen2014** [comment]
i never used blazor binding , can you sent me a little demo project for debug?

for me,if don't user in original browser,i choose xanarim form o uni-app for scan barcode

**Comment by rajeshsws** [comment]
Hi
Though  webapi I m getting data.
When it run in Android emulator it do not work as well on internet.
I tried both http client  http and https.
Once again thank you for your responses

**Comment by densen2014** [comment]
so your h5/js codes is run in android local devices? blazor binding just named like blazor but not a blazor wasn neither blazor ssr right? when this js codes no run in browser original in android,it can't work ,because video label only works in browser,no works in webview control.

**Comment by rajeshsws** [comment]
Ok i got your points.
Do you have any future  plan to make it for webview.?
Thank you

**Comment by densen2014** [comment]
can you tell me how to run your blazor binding now?is webpage local or is a app like xamarin or something?

**Comment by rajeshsws** [comment]
Its like xamarin cross platform app.which run like xamarin. I will share
you source code in my next email

**Comment by densen2014** [comment]
so maybe use xamarin essentials something cross image project better

**Comment by densen2014** [comment]
like this

if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await Application.Current.MainPage.DisplayAlert("没检测到摄像机或者无权限", "去开一下权限，或者只使用图库。", "打开权限", "只使用图库");
                CrossPermissions.Current.OpenAppSettings();
                return null;
            }
            var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
            var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);

            if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
                cameraStatus = results[Permission.Camera];
                storageStatus = results[Permission.Storage];
            }

**Comment by rajeshsws** [comment]
Hi Alex
Please download the source code and check what you do.
*https://wetransfer.com/downloads/cb7790750385f1601a8cbf5edc56756220201217094210/84313e
<https://wetransfer.com/downloads/cb7790750385f1601a8cbf5edc56756220201217094210/84313e>*
*Once again thank you for your prompt response*
Thank You

Best Regards
Rajesh Shoky (9716000503)
Methods Apparel Consultancy India Pvt Ltd.
Vipul Business Park
Suite :1016, 10th floor
Sector 48
Gurugram-122001
Skype ID : shoky114
Linked In :LinkedIn.com/in/rajeshsheokand
what's App :+919716000503

**Comment by rajeshsws** [comment]
Hi  Alex
Where I need to Copy this code as i cna see in Xamarin, there is no such class Crossmedia and CrossPermission.
var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
Thank you

**Comment by densen2014** [comment]
> Hi Alex
> Where I need to Copy this code as i cna see in Xamarin, there is no such class Crossmedia and CrossPermission.
> var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
> var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
> Thank you

visit  https://github.com/Redth/ZXing.Net.Mobile

**Comment by rajeshsws** [comment]
Hi Alex
I have already tried this lib and it is working fine in Xamarin only
project not in Mobile blazor binding.I am looking for Blazor Lib for
Webview in Xamarin.
Again a very big thanks for your response.
If you make any MobileBlazorbinding project in future and use QR code
please let me know
Thank you


Best Regards
Rajesh Shoky (9716000503)
Methods Apparel Consultancy India Pvt Ltd.
Vipul Business Park
Suite :1016, 10th floor
Sector 48
Gurugram-122001
Skype ID : shoky114
Linked In :LinkedIn.com/in/rajeshsheokand
what's App :+919716000503

**Comment by rajeshsws** [comment]
Hi
My problem Solved. Camera is working in Mobile Blazor Binding with Zxing.mobile.
 **ZXing.Mobile.MobileBarcodeScanner.Initialize(Application);**
in Main Activity.cs
Thank you

**Comment by densen2014** [comment]
> 嗨，
> 我的问题解决了。Camera正在使用Zxing.mobile在Mobile Blazor绑定中工作。
> **ZXing.Mobile.MobileBarcodeScanner.Initialize（Application）; **
> 在Main Activity.cs中
> 谢谢

is a good news!
