### ISSUE TITLE
Can not decode PDF417 format type?

### ISSUE THREAD

**Issue by binhtt6** [densen2014/ZXingBlazor#21]
Hello, i try demo but get no luck with PDF417? Could you take a look about it? Thanks

**Comment by densen2014** [comment]
maybe need to config with zxing libs，i will check later

**Comment by binhtt6** [comment]
Thanks, waiting for further information

**Comment by densen2014** [comment]
**Support now:**

demo
https://zxingblazor.app1.es/

pack
https://www.nuget.org/packages/ZXingBlazor/0.2.4

use Pdf417="Pdf417"

```
    <BarcodeReader ScanResult="((e) => { BarCode=e; ShowScanBarcode = !ShowScanBarcode; })"
                   ShowScanBarcode="ShowScanBarcode"
                   Close="(()=>ShowScanBarcode=!ShowScanBarcode)"
                   ScanBtnTitle="Scan"
                   ResetBtnTitle="Reset"
                   CloseBtnTitle="Close"
                   Pdf417="Pdf417"
                   SelectDeviceBtnTitle="Select Device" />

```

![image](https://user-images.githubusercontent.com/8428709/203292744-7a9f1d48-0b91-4950-a5f5-55bf7f9f97d9.png)

**Test:**
https://www.dynamsoft.com/use-cases/driver-license/assets/Image_2.png

**Video:**
https://youtube.com/shorts/ia0JMdcHfJs

**Comment by binhtt6** [comment]
Thanks for your update. Trying decode with your png file in demo website but no luck. Demo web can decode QR code as well.

**Comment by densen2014** [comment]
- [x] do you test with checkBox “pdf417” is on？

- [x] or “Decodde all formats” is on to test it.


![image](https://user-images.githubusercontent.com/8428709/203590150-da696668-e7a1-4172-a4cd-46613b9aea8a.png)

or

![image](https://user-images.githubusercontent.com/8428709/203590202-ba9f047d-20d7-40cc-b16d-672b15674047.png)

**Comment by binhtt6** [comment]
https://user-images.githubusercontent.com/30441291/203741660-3fa20fc9-1a5e-49b0-a4d6-9cba9df3abfd.mp4

Here is what i tested from my site

**Comment by densen2014** [comment]
> 
> 
> https://user-images.githubusercontent.com/30441291/203741660-3fa20fc9-1a5e-49b0-a4d6-9cba9df3abfd.mp4
> 
> 
> 
> Here is what i tested from my site

what version is your android？ pdf417 need browse support bigint， can you test again in a ios device？

**Comment by densen2014** [comment]
i will do some test in android

**Comment by densen2014** [comment]
do a test like my video: close the phone slowly to your papel , it has a distance setting for decode


Video:

![image](https://user-images.githubusercontent.com/8428709/203809372-efd7353b-634e-4929-ba90-af36a87ab83b.png)


https://user-images.githubusercontent.com/8428709/203809313-52491cf5-5b6a-4c46-8c67-5c90df5ba22b.MOV

https://user-images.githubusercontent.com/8428709/203809350-e8bf2ecb-3e5b-4159-ae90-12152c75a7e1.MOV

**Comment by densen2014** [comment]
Hahaha, in my new test !  pdf417 can be decoded all the time like version 0.2.3,  new version 0.2.6 adds a **Pdf417Only** setting limit to only scan this type of code, corresponding to a special scene where there are many barcode types on a picture

**Comment by binhtt6** [comment]
Hello, after update my chrome mobile to newest version ( my os is Android 12). Web demo can decode pdf417 without Pdf417Only  checkbox.
But it seems not stable, take time to decode (3-4 s) , not smooth as decoding QR code.
Can we optimize this ?
i also try an android app https://play.google.com/store/apps/details?id=mobi.pdf417&hl=vi&gl=US
it can decode so fast.
Thanks

**Comment by densen2014** [comment]
app is alway working fast then web browser， ： ）

**Comment by densen2014** [comment]
The scanning distance is the key factor, and you can quickly scan the code after more tests.  Another parameter is the interval between two scan codes, you can check the source code yourself
