### ISSUE TITLE
FlashLight Compatibility

### ISSUE THREAD

**Issue by JulienMontfort** [densen2014/ZXingBlazor#22]
Hello, 

Is it planned to be compatible with the phone's torch?
It is convenient to scan a qr code in dark places.

I use the Blazor on a MAUI application. When I turn on the flashlight with the MAUI APIs, when the ZXingBlazor componant is launched, the torch turns off automatically.
When i use MAUI flashlight in other pages, no issue.

This makes me think that the ZXingBlazor component takes over the control of the light, and sets it to off by default.
 
What is the correct way to use the torch during the scan?

**Comment by densen2014** [comment]
maui you can use the app native function for scan barcode with lights， with zxing.js maybe can not do that， ：）

**Comment by densen2014** [comment]
for example zxing xamarin


![image](https://user-images.githubusercontent.com/8428709/204005324-86d6ea07-6ad2-4108-9a9f-92e422e0c03b.png)

**Comment by JulienMontfort** [comment]
Hi densen2014,

I have allready try to ZXing.Net.MAUI but ZXingBlazor has a much better accuracy.  I have not seen better. 

I'll try anyway zxing xamarin. 

I have seen in this link [https://codepen.io/adamrifai/pen/YLxjKa](url) but I'm not skilled enough in javascript to modify this project.

If you ever find a solution I'm interested ^^

**Comment by densen2014** [comment]
for js open torch ，i need do some research ， tks for your issue

**Comment by densen2014** [comment]
https://github.com/sabitertan/BlazorBarcodeScanner/blob/master/BlazorBarcodeScanner.ZXing.JS/wwwroot/BlazorBarcodeScanner.js

**Comment by densen2014** [comment]
@JulienMontfort can you do a test with this url?
https://densen.es/test/webdev/camera/

ImageCapture.getPhotoCapabilities() => fillLightMode : Returns an array of available fill light options. Options include auto, off, or flash.

But It can only work in Chrome, because ImageCapture is only supported in Chrome and Opera

**Comment by JulienMontfort** [comment]
@densen2014 
With your URL the flash button not work while it work with my link.

**Comment by densen2014** [comment]
> @densen2014 With your URL the flash button not work while it work with my link.

so `torch`  is a very small function, not universal. i cann't do anything.
