### ISSUE TITLE
NotAllowedError: Permission Denied for Maui Blazor when run in Android.

### ISSUE THREAD

**Issue by tricuongle** [densen2014/ZXingBlazor#27]
I use your nuget for Maui Blazor, it run in window is ok. 
But for android it is error: NotAllowedError: Permission Denied.
(I sure I allow access camera for  this program. )

**Comment by tricuongle** [comment]
![image](https://github.com/densen2014/ZXingBlazor/assets/54373361/bf35c4a4-9532-4212-ad97-5ad2f9889c81)

**Comment by densen2014** [comment]
you need handel your maui webview  Permission , you can find some answer in
here https://github.com/densen2014/BlazorMaui

Le Tri Cuong ***@***.***> 于2023年6月22日周四 21:32写道：
