### ISSUE TITLE
video tag style bug

### ISSUE THREAD

**Issue by yongkeecho** [densen2014/ZXingBlazor#28]
Hi. Thank you for the great component.
I found the style is defined out of video tag at https://github.com/densen2014/ZXingBlazor/blob/57965df36cf0b2714a7f5a4d2ee87f99a692569d/src/ZXingBlazor/Components/BarcodeReader.razor#L29
video tag is already closed at line 28.

**Comment by densen2014** [comment]
wow that is a mistake ，thanks for your response!

**Comment by densen2014** [comment]
ZXingBlazor 1.0.1 fixed
