### ISSUE TITLE
Error: Could not find 'zxing.start' ('zxing' was undefined)

### ISSUE THREAD

**Issue by gigimaister** [densen2014/ZXingBlazor#3]
Hi.
This after I added scripts in Index(Blazor WASM) and in _ViewImports..
Any Idea?

**Comment by densen2014** [comment]
try run my demo project first

**Comment by gigimaister** [comment]
Yes..Because I didn't have camera on my pc.
Thank you so much Sir.
Also, can I change the modal style? And the buttons language?

**Comment by cyberdarius** [comment]
The import in index.html of js is incorrect:

working one is (ZXing.Blazor) with dot and not (ZXingBlazor)

    <script src="_content/ZXing.Blazor/lib/barcodereader/zxing.js"></script>
    <script src="_content/ZXing.Blazor/lib/barcodereader/barcode.js"></script>

**Comment by densen2014** [comment]
> Yes..Because I didn't have camera on my pc.
> Thank you so much Sir.
> Also, can I change the modal style? And the buttons language?

You can modify the distribution freely

**Comment by densen2014** [comment]
> The import in index.html of js is incorrect:
> 
> working one is (ZXing.Blazor) with dot and not (ZXingBlazor)
> 
> ```
> <script src="_content/ZXing.Blazor/lib/barcodereader/zxing.js"></script>
> <script src="_content/ZXing.Blazor/lib/barcodereader/barcode.js"></script>
> ```

i was added a project with NugetPackage:
https://github.com/densen2014/ZXingBlazor/blob/master/demoWithNugetPackage/BlazorApp1/wwwroot/index.html
```
    <script src="_content/ZXingBlazor/lib/barcodereader/zxing.js"></script>
    <script src="_content/ZXingBlazor/lib/barcodereader/barcode.js"></script>
```
