### ISSUE TITLE
Difference between a barcode and qr

### ISSUE THREAD

**Issue by KSDev31** [densen2014/ZXingBlazor#30]
Hi densen! I would like to know if it is possible to differentiate between a barcode and a QR code?

**Comment by densen2014** [comment]
what did you want?only decode 1d or 2d?

**Comment by KSDev31** [comment]
I currently decode 1D, but I need to know if they can be differentiated so that a 1D is not entered where a QR goes

**Comment by densen2014** [comment]
It seems to be a false requirement, but we can give you a parameter setting to only decode 1D or 2D.

what did you think?

**Comment by KSDev31** [comment]
It worked sending you the formats, I wasn't sure what to do. I went back through the files on your site to test the library and got it. thank you very much!
