### ISSUE TITLE
Scan invert QR code not working?

### ISSUE THREAD

**Issue by Tham25** [densen2014/ZXingBlazor#31]

**Comment by Tham25** [comment]
e.g: white code on black, green or red background

**Comment by densen2014** [comment]
yes。zxing is can not decode non black color code. i will do some research. tks

**Comment by Tham25** [comment]
White code on black background

Vào 14:16, Th 4, 16 thg 8, 2023 Alex chow ***@***.***> đã
viết:

**Comment by Tham25** [comment]
can you show me the code that the camera detect the QR code

**Comment by densen2014** [comment]
I did a lot of searching and there is no good solution to this problem

**Comment by densen2014** [comment]
zxing api has this hint, but zxing.js haven't 

![C91AWDV7AERXL3{PZI@2ENA](https://github.com/densen2014/ZXingBlazor/assets/8428709/26843a62-d1d3-4fb6-903b-6d86376f7f85)
