### ISSUE TITLE
PC camera does not display image consistently

### ISSUE THREAD

**Issue by KevinLandgrave** [densen2014/ZXingBlazor#4]
iOS and android browsers work, but debugging in Visual Studio on PC, or clicking the demo links in this repo, the site does not show camera image in the square below the 3 buttons.  It's a solid dark green color.  If I click on the buttons enough the image comes up, but the screen thinks I have aborted without scanning, do it apparently does not try to scan anymore.

I have allowed the different site locations to access the camera, do that is not the problem. 

I use the camera on the PC for Zoom and video and picture capture all the time with no issues.

The zxing camera issue happens on both the WASM and Blazor Server versions.

**Comment by densen2014** [comment]
Is this the same with my demo? What browser are you using? If deployed to the internet, **https** forcibly
