### ISSUE TITLE
Change to English? 

### ISSUE THREAD

**Issue by vinit21** [densen2014/ZXingBlazor#5]
Hello ,

It is beautiful project and perfectly working. Just few buttons are displayed in Chinese. How do I change to english? I am using Blazor Wasm.

**Comment by yiyoMX** [comment]
I support this.

**Comment by densen2014** [comment]
you can take the source code change lable or something you want, no ploblem

**Comment by densen2014** [comment]
now support set button text:
code
https://github.com/densen2014/ZXingBlazor/blob/master/Demo.Server/Pages/IndexEN.razor
demo
https://zxingblazor.app1.es/

```
    <BarcodeReader ScanResult="((e) => { BarCode=e; ShowScanBarcode = !ShowScanBarcode; })"
                   ShowScanBarcode="ShowScanBarcode"
                   Close="(()=>ShowScanBarcode=!ShowScanBarcode)" 
                   ScanBtnTitle="Scan"
                   ResetBtnTitle="Reset"
                   CloseBtnTitle="Close"
                   SelectDeviceBtnTitle="Select Device"
                   />
```

![barcode](https://user-images.githubusercontent.com/8428709/118119633-f6416000-b3ee-11eb-8537-ec356242f63b.jpg)

**Comment by yiyoMX** [comment]
Awesome! Thanks.
