### ISSUE TITLE
Doesn't open camera stream on iOS

### ISSUE THREAD

**Issue by mehowq** [densen2014/ZXingBlazor#6]
Tried it on IPhone7 safari, chrome, firefox, edge and opera. None of the browsers open  the video stream. Any chance to fix this?

**Comment by densen2014** [comment]
only work in https and safari

**Comment by mehowq** [comment]
Thanks for the reply. Just tested it and I'm still getting black screen initially, even in https:
![20210512_063854](https://user-images.githubusercontent.com/24491572/117924479-b8a8de00-b2ed-11eb-955a-e154d23431cb.jpg)

But I found if I press the power button at this stage to turn the screen off and press it again to turn the screen on, I can see the video stream and scan. But after a successful scan, the stream goes to black screen again and I need to press power again to make it work.

Any ideas?

**Comment by densen2014** [comment]
try my Demo

ssr https://zxingblazor.app1.es

wasm https://densen2014.github.io/

**Comment by mehowq** [comment]
Thanks, unfortunately still the same:
![IMG_4318](https://user-images.githubusercontent.com/24491572/118120847-71ebde80-b3e8-11eb-8231-67c8fa49a5ac.jpg)
![IMG_4319](https://user-images.githubusercontent.com/24491572/118120859-76b09280-b3e8-11eb-8f67-39a0dd73f369.PNG)

**Comment by densen2014** [comment]
yes, something wrong when run in new ios, we will fix it as soon as possible, thank you for report issues.

**Comment by Lanticee** [comment]
I got same problem, but I found if you open camera,then use change app to others app..then switch back browser...camera .it will works....hope it can be fixed...

**Comment by densen2014** [comment]
ok

**Comment by pradeep-w** [comment]
Same here. Tried on iOS 14.5.1. (iPhone 11) - the camera _**preview is blank - but the component is working and detecting the barcode.**_ So the problem is with the rendering of the preview. Also as @Lanticee  noted, if you keep the any other camera app open in the background and switch to this component, the live preview appears correctly. 

Great component btw ! Please try to fix the issue. 
Thanks !

**Comment by Pant76** [comment]
Same problem here....any solution?

**Comment by sarahrbs** [comment]
I have got the same problem, its a great component though. May I know the timeline to fix this issue as I plan to use in my project? Thanks.

**Comment by FrankMuessner** [comment]
Hi there,
have the problem too. Will there be an exam?

**Comment by densen2014** [comment]
i was Upgrade to js isolated version, add image browser Viewer component, and upgrade demo project to net6 format
