### ISSUE TITLE
Could not load index.min.js.map

### ISSUE THREAD

**Issue by eldeo** [densen2014/ZXingBlazor#8]
When I download the source code, open the solution in Visual Studio 2019, set Demo.Wasm as default project and run, I get the following error:

DevTools failed to load source map: Could not load content for https://localhost:44341/_content/ZXingBlazor/lib/barcodereader/index.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by densen2014** [comment]
i was Upgrade to js isolated version, add image browser Viewer component, and upgrade demo project to net6 format

**Comment by parente89** [comment]
I created a webassmbly project with .net6 and Zxing version 0.2, but I get the above error when opening the page when it is published on IIS.  It works very well when I launch it with VisualStudio.  How can I solve the problem?

**Comment by densen2014** [comment]
*.map not is a problem。

step by step follow this page

https://github.dev/densen2014/ZXingBlazor
