### ISSUE TITLE
Autofocus doesn't work / scanning takes very long

### ISSUE THREAD

**Issue by connor-peters** [densen2014/ZXingBlazor#9]
Hi, I'd like to use ZXingBlazor for a DMC scanner app. My problem is, that the DMC is very small and printed on a rubber product. So it's basically an inverted data matrix code on a rough and shiny surface. I need to hold the camera very close to the product (approx. 5cm) to have the DMC in a frame. Unfortunately, the picture is very blurred and the camera doesn't focus. It is possible to receive a result when holding the iPhone like 10cm away from the product, but it takes some time and you need to try different angles. Is there a way to achieve a better performance? 
Thanks in advance!

**Comment by densen2014** [comment]
You can try to change the source code. I haven't read the ZXing.js document very carefully. and i was Upgrade to js isolated version, add image browser Viewer component, and upgrade demo project to net6 format
